Repository the-turing-index/web-app, pull requests merged in 2020-11, with the labels that each got.

#43 Feature/nl/fetch data
  src/app/map/get.model.ts
  src/app/map/map.component.html
  src/app/map/map.component.spec.ts
  src/app/map/map.component.ts
  src/app/modal-classroom/modal-classroom-dialog.component.html
  src/app/modal-classroom/modal-classroom.component.ts
Labels: Angular, Sprint 3, front end

#47 Feature/jcs/heading revamp
  .DS_Store
  README.md
  src/app/app.component.html
  src/app/app.component.scss
  src/app/heading/heading.component.html
  src/app/heading/heading.component.scss
  src/app/heading/heading.component.spec.ts
  src/app/heading/heading.component.ts
  src/app/map/map.component.html
  src/app/map/map.component.scss
  src/app/map/map.component.ts
  src/app/modal-classroom/modal-classroom-dialog.component.html
  src/app/modal-classroom/modal-classroom.component.ts
  src/assets/docImages/sprint3Landing.png
  src/material.module.ts
  src/sass/abstracts/_variables.scss
  src/sass/base/_base.scss
  src/sass/components/_button.scss
  src/sass/layout/_navigation.scss
  src/styles.scss
Labels: Angular, Sprint 4, Testing, enhancement

#54 Style/buttons comp
  src/app/app.module.ts
  src/app/buttons/buttons.component.html
  src/app/buttons/buttons.component.scss
  src/app/buttons/buttons.component.spec.ts
  src/app/buttons/buttons.component.ts
  src/app/heading/heading.component.scss
  src/app/map/map.component.html
  src/app/map/map.component.scss
  src/app/map/map.component.ts
Labels: Angular, bug, front end

#55 Feature/nl/position buttons
  src/app/map/map.component.html
  src/app/map/map.component.scss
  src/sass/base/_base.scss
Labels: Styling

#56 Style/radiate buttons
  src/app/map/map.component.html
  src/app/map/map.component.scss
Labels: Angular, front end

#58 Feature/jcs/modal style
  src/app/map/map.component.html
  src/app/map/map.component.scss
  src/app/map/map.component.ts
  src/app/modal-classroom/modal-classroom-dialog.component.html
  src/app/modal-classroom/modal-classroom.component.html
  src/app/modal-classroom/modal-classroom.component.ts
  src/sass/abstracts/_variables.scss
Labels: Angular, bug, enhancement

#53 Feature/jcs/testing
  src/app/about/about.component.spec.ts
  src/app/app.module.ts
  src/app/map/map.component.spec.ts
  src/app/map/map.component.ts
  src/app/modal-classroom/modal-classroom.component.spec.ts
  src/app/page-not-found/page-not-found.component.spec.ts
  src/assets/floorplan.svg
Labels: Testing

#61 Feature/jcs/bug spray
  src/app/map/map.component.html
  src/app/map/map.component.ts
  src/app/modal-classroom/modal-classroom-dialog.component.html
  src/app/modal-classroom/modal-classroom.component.ts
  src/shared/DemoData.ts
  src/shared/mockData.ts
Labels: Angular, bug, enhancement

#62 Feature/jcs/final push
  src/app/app-routing.module.ts
  src/app/app.component.spec.ts
  src/app/heading/heading.component.scss
  src/app/heading/heading.component.spec.ts
  src/app/map/map.component.html
  src/app/map/map.component.ts
  src/app/modal-classroom/modal-classroom-dialog.component.html
  src/app/modal-classroom/modal-classroom.component.spec.ts
  src/app/modal-classroom/modal-classroom.component.ts
  src/shared/DemoData.ts
  tslint.json
Labels: Angular, Testing, enhancement
